### ISSUE TITLE
Testing 0.8.1

### ISSUE THREAD

**Issue by ghost** [ChadBailey/videospeed-refactoring#1]
Re: https://github.com/igrigorik/videospeed/issues/964 , posting the issue here since it is kind of a wall of text...
This is a dirty test, I am mainly checking for differences between 0.7.1 and 0.8.1 while leaving my other extensions as-is.

General-

- Seems to work about the same in most of the sites I had been using 0.7.1 with (Twitter, Youtube, Twitch, Vimeo, direct links).
- Doesn't seem to work on some sites that 0.7.1 does work on:
https://developers.google.com/youtube/youtube_player_demo
https://docs.microsoft.com/en-us/training/modules/describe-azure-compute-networking-services/5-containers
https://www.reddit.com/r/videos/comments/x8bas6/martin_scorcese_picks_up_his_photos_from_the/
(unsure about the scope of this problem, I don't often run across embedded videos outside of the major platforms and had to do some searching to find these examples. Apologies if I'm missing something obvious.)
It is working on these sites:
https://simonschreibt.de/gat/mafia-ii-hat-vs-hair/
https://www.nlm.nih.gov/web/documentation/TemplateDocumentation/videojs_basic.html
- Regex seems to be working with the one regex item I have (after closing it properly due to regex fixes).
- Hotkey/UI-button to hide VSC UI doesn't work, "Settings> Hide controller by default> enabled" doesn't work.
- Other functions seem to be working. (Have not tested the Pause or Marker-related functions since I don't have any experience with those.)

Twitch- 

- Pausing video and mousing over video draws an opaque blue rectangle over the entire video / under the UI.
Persists even when extension is disabled via Enable/Disable button or "Settings> Enable> disabled" or site-disable list.
- A small portion of the 'Alt+P'-invoked navigation menu is always visible in the top-left corner.

YouTube- 

- Mousing over most video UI buttons draws an opaque blue rectangle (with rounded corners) under the moused-over button (but not over the entire video, as with Twitch).

All of these are pretty minor to me, excepting (maybe) the embedded video problem. Will keep testing.
Thank you for your hard work!

**Comment by ChadBailey** [comment]
Thanks so much for taking the time out to test! I'll look into the issues you found

**Comment by ghost** [comment]
Found something else, in several cases webpage rendering changes with 0.8.1 (compared to 0.7.1 or no VSC extension).

![20220908-154241](https://user-images.githubusercontent.com/13858149/189238846-cc94a6db-bd7c-42db-a23d-88268bb6d356.gif)
(Trying with new install of Chrome Portable, only VSC 0.7.1 + 0.8.1 installed, default settings.)

Have only checked a few sites, so far it seems a little random. On YouTube and Twitter, various bits of text and UI change (but not significantly). The Github example is the most extreme so far, but it doesn't seem to extend to this issue post.

**Comment by ChadBailey** [comment]
Great catch, I think I see what the problem is with this (and I think the twitch issue is related)... I'll try and get it figured out tonight if I can

**Comment by ChadBailey** [comment]
Here's my list, I'll keep it updated (any outsiders reading this - PR's are encouraged!)

- [x] Inappropriate restyling of page elements
- [ ] Embedded video support
- [ ] UI toggle hotkey broken

**Comment by ChadBailey** [comment]
Issue #1 (Inappropriate restyling of page elements) has been identified, but the root cause may be deeper and no remediation yet. 

The lines in `shadow.css` here are poisoning the main document rather than staying part of the shadowroot.
https://github.com/ChadBailey/videospeed-refactoring/blob/ff9603a8fb44923bc31295e6af671f33767244d0/src/assets/css/shadow.css#L1-L5

I don't really like the way this is written anyway, so I may be rewriting it. More to come.

**Comment by ChadBailey** [comment]
Issue #2 fixed... it was erroneously added wholesale as a content css script making it apply to every single page you visited. Depending on how that particular page styled it was either noticeable or not. I removed it, and it fully resolved the issue. No need to rewrite anything, we can save those "nice to have" updates for a rainy day.

As an aside, I think this was also configured this way in the main version but was broken - I've found many things in this exercise that weren't working as intended in the main version (like the controller attempting to auto-hide but failing) so not terribly surprising.

**Comment by ChadBailey** [comment]
All done! Please check the 0.8.2 release once it's live on the chrome web store and confirm with me if the problems have been fixed so I can close this out.

**Comment by ChadBailey** [comment]
looks like it's now live @ https://chrome.google.com/webstore/detail/video-speed-controller-be/kgciknbfdanakgjeeoihchpljcejkkdj?hl=en&authuser=1

**Comment by ghost** [comment]
Took a quick look, seems like all the issues I brought up have been resolved. Thank you! Will keep using it and report back if anything else comes up.
Unsure if I'm supposed to close this issue now, but it seems like the appropriate thing to do.

**Comment by ChadBailey** [comment]
awesome! you're right, since all the issues are resolved it's appropriate to close. if you find a new issue please open a new one
